version: '3.8'

services:
  terraform:
    image: hashicorp/terraform
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY=ASIAWKNI5U66QCK7MIMO
      - AWS_SECRET_ACCESS_KEY=MZvShhFs1YyKG5qnCo44QqPKQ5DYogTjCl6tppob
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjECEaCXVzLWVhc3QtMSJIMEYCIQDBk0YtQhlfeX+4OQG2KrnwDKxZ0aPAtKeHFMyZmvKSjwIhANUZIKBRcZaurcQMasnDg0udzvR3AMEERIVKGR/wQ4ZNKogDCKn//////////wEQABoMNDM0NjgyODMyODI5IgznvDGIq7H68vuvsEAq3AKDzjgUnCxgpvIAmu6m/AFr2id5eou6h9+R18+HgEyQAV4Qkv1VGHJ9zKQk08myJVAe8+tL3FDIrpdFtBRHWkRV5Nab7LUzDNPkVPDB4cZ2OSqpRfEJTV+xQrNQfww7vHbCaq8adiZ/OV/gmeoF//FW22ByeCX47E13OJl+WfUGA6364nUzR3mSVcO86PyCdO5cERXO+NfUiIQbJ8MmvYxsq1EaBYSLFZKTWD/XUZxFkUgZMxpOl8HGCXAD3vIuSh92uA+hXgXmR5oiVzOzJda9PcypGmiLKGayZC4OKvxqaeuHCPcN4DZGRUqIYStByUk4GxmkiYBY9K1xIZLfnClsepi1yJzx0fjMKdVHTJKTgF5G8qnJjFL4l/NGqZFKfdKELwoRiAMpAySTgBghJv2QppZbbN5ykTxHDYJjPpN++cIfc6yFodBfd8NlmCmorEHjo/sjkMpAIBVHbu4wntbqhAY6pQElSUkEXLSnQhO0mq0uc+2IbzZnSnGTwol7QJ3Pz/hoLYnEuS2J7Ns656+1sPoDMyLtXCzGvVKHOYhSzyVSqSaK3ASV092PW/iinRs4QmOhTE2TX1L6f0aEuOu5fVnuqcok6CEuudExfBCFNPvLjFvO5jaPJ9/AGD2LCT65eOnVDN6xR9L1lsJ+zX2RvUtOQl9gn3ztxMFqnDI3bJ5dGE+OJsrwzZY=
