version: '3.8'

services:
  terraform:
    image: hashicorp/terraform
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY=ASIAWKNI5U66V5WXVTG5
      - AWS_SECRET_ACCESS_KEY=/AxOKh8bm2SdZoAoXz7EpyeqlhLgdta91T6W3Efq
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEPz//////////wEaCXVzLWVhc3QtMSJHMEUCIQDd9APQ/d/WKHpl0bJBfNz+6K9Kx0Ux20hpaZD/iPNqiwIgfXshX1IEKH5qiJuEBCoBx4GWRZilsYjKuAfzllJVUxMqiAMIhf//////////ARAAGgw0MzQ2ODI4MzI4MjkiDI2JM6RRnEIN2cHCfCrcAq+1VBUbyeNeeDDgj7PB+w6g1ukPZRtwAijKQkG+HIQSh/3fm1FjZSiSCEwGRrzEgKGaw7xcXB4VdgOuTDUYREnxcOxAJVcp2brQwhcDKWcfgYNPIAxgP0Khm52ZystIYCV7EybYO8AMr54dabETEqSDmn5+J0xEOpltsSokhIwiDVHJIskJ7rxkTgMIDeRmIWFICnyV+6SaS0SsU3p72TGmjb9L8Aq0TSZ8tRm4tkWBuKGIDrU8KObK5goaQKglFXa7TH2l6+GxJLZZIeH5yB+3/VrK7sNCVhBp74i0lPiXLj+rC4XyYONNqyGB29YPbsOA3xjk6uT7ldh4TO7K6deDHMpDPHD541STwvXAIDm6eKjIiMMVmwon5j2YQLYUL1mAAaFS+XYClfdVzJfPGm9h23XA6Z1BHpAVM3BSYFgAhPlSJmjXyPYvmHwX58oH556QMJy8N0fv5/9RxzDI2uKEBjqmAeUaJmLxNGL0tVgULkAL8CLDzsTx00Ku5dG6KxHR050y68J9ao5cK3BrPm559hxqQ3whR0NdH55EfPm25ytMrvO/y3xeV0xsVkGlhb6LiLeEnKc+r6M8fF2mt0hHVXal93TCCUxL7Ypp7YGZaIpWl2tFlper72FHSkhRn7txikuXK5XXx0A5f1X55i65gq3KopE+dzWLpsBGezRknrBA+fz2BiKFuCY=
