version: '3.8'

services:
    terraform:
        image: hashicorp/terraform:0.15.3
        volumes:
            - .:/infra
        working_dir: /infra
        environment:
            # AWS SECRET KEY